#include <algorithm>
#include <functional>
#include <iostream>
#include <map>
#include <numeric>
#include <set>
#include <tuple>
#include <vector>
using namespace std;struct Pt{int x,y;bool operator<(Pt const&o)const{return tie(x,y)<tie(o.x,o.y);}bool operator==(Pt const&o)const{return x==o.x&&y==o.y;}};long long cross(Pt a,Pt b,Pt c){return 1LL*(b.x-a.x)*(c.y-a.y)-1LL*(b.y-a.y)*(c.x-a.x);}pair<int,int>dir(Pt a,Pt b){int x=b.x-a.x,y=b.y-a.y,g=gcd(abs(x),abs(y));x/=g;y/=g;if(x<0||(x==0&&y<0))x=-x,y=-y;return{x,y};}bool del(vector<Pt>const&all,vector<Pt>D,unsigned long long&t){sort(D.begin(),D.end());set<Pt>ds(D.begin(),D.end());vector<Pt>b;for(auto p:all)if(!ds.count(p))b.push_back(p);sort(b.begin(),b.end());vector<int>xs,ys;for(auto p:D)xs.push_back(p.x),ys.push_back(p.y);sort(xs.begin(),xs.end());sort(ys.begin(),ys.end());vector<Pt>g;map<Pt,int>ix;for(int x:xs)for(int y:ys){Pt p{x,y};if(!ix.count(p))ix[p]=g.size(),g.push_back(p);}vector<char>ok(g.size(),1);vector<vector<char>>pk(g.size(),vector<char>(g.size(),1));for(int i=0;i<(int)g.size();i++){if(binary_search(b.begin(),b.end(),g[i])){ok[i]=0;continue;}set<pair<int,int>>d;for(auto q:b)if(!d.insert(dir(g[i],q)).second){ok[i]=0;break;}}for(auto r:b){map<pair<int,int>,vector<int>>m;for(int i=0;i<(int)g.size();i++)if(ok[i])m[dir(r,g[i])].push_back(i);for(auto&e:m)for(int i=0;i<(int)e.second.size();i++)for(int j=i+1;j<(int)e.second.size();j++)pk[e.second[i]][e.second[j]]=pk[e.second[j]][e.second[i]]=0;}do{t++;vector<Pt>A;vector<int>z;set<Pt>u;bool q=1;for(int i=0;i<(int)D.size();i++){Pt p{xs[i],ys[i]};if(!u.insert(p).second){q=0;break;}int v=ix[p];if(!ok[v]){q=0;break;}A.push_back(p);z.push_back(v);}if(!q||u==ds)continue;for(int i=0;i<(int)A.size()&&q;i++)for(int j=i+1;j<(int)A.size();j++)if(!pk[z[i]][z[j]])q=0;for(int i=0;i<(int)A.size()&&q;i++)for(int j=i+1;j<(int)A.size();j++)for(int k=j+1;k<(int)A.size();k++)if(cross(A[i],A[j],A[k])==0)q=0;if(q)return true;}while(next_permutation(ys.begin(),ys.end()));return false;}int main(){int J;cin>>J;while(J--){string id;int n,b,k;cin>>id>>n>>b>>k;vector<Pt>a(n),c(k);for(auto&p:a)cin>>p.x>>p.y;for(auto&p:c)cin>>p.x>>p.y;set<Pt>cs(c.begin(),c.end());vector<Pt>av;for(auto p:a)if(!cs.count(p))av.push_back(p);int e=b-k;vector<Pt>ch;bool f=0;unsigned long long t=0;function<void(int,int)>go=[&](int s,int l){if(f)return;if(!l){auto D=c;D.insert(D.end(),ch.begin(),ch.end());if(del(a,D,t))f=1;return;}for(int i=s;i<=(int)av.size()-l&&!f;i++)ch.push_back(av[i]),go(i+1,l-1),ch.pop_back();};go(0,e);cout<<"RES "<<id<<" "<<f<<" "<<t<<"\n";}}
