#include <algorithm>
#include <array>
#include <cstdint>
#include <deque>
#include <iostream>
#include <map>
#include <numeric>
#include <set>
#include <unordered_map>
#include <vector>
using namespace std;
struct P{int x,y;}; inline long long cr(P a,P b,P c){return 1LL*(b.x-a.x)*(c.y-a.y)-1LL*(b.y-a.y)*(c.x-a.x);}
array<P,4> blk(int m,int s,int t,int e){int n=2*m;auto r=[n](int x){return n-1-x;};P q0{s,e?r(t):t},q1{r(s),e?t:r(t)};return {q0,q1,P{r(q0.y),q0.x},P{r(q1.y),q1.x}};}
bool pairbad(int m,int sa,int ta,int ea,int sb,int tb,int eb){auto a=blk(m,sa,ta,ea),b=blk(m,sb,tb,eb);array<P,8>p{};for(int i=0;i<4;i++){p[i]=a[i];p[i+4]=b[i];}for(int i=0;i<8;i++)for(int j=i+1;j<8;j++)for(int k=j+1;k<8;k++)if(cr(p[i],p[j],p[k])==0)return true;return false;}
int triplecount(int m,int a,int ta,int ea,int b,int tb,int eb,int c,int tc,int ec){auto A=blk(m,a,ta,ea),B=blk(m,b,tb,eb),C=blk(m,c,tc,ec);int q=0;for(auto x:A)for(auto y:B)for(auto z:C)q+=cr(x,y,z)==0;return q;}
struct Rel{int m;vector<int8_t>d;Rel(int M):m(M),d(m*m*m*m,0){for(int a=0;a<m;a++)for(int ta=0;ta<m;ta++){if(ta==a)continue;for(int b=a+1;b<m;b++)for(int tb=0;tb<m;tb++){if(tb==b||tb==ta)continue;bool e=pairbad(m,a,ta,0,b,tb,0),u=pairbad(m,a,ta,0,b,tb,1);d[idx(a,ta,b,tb)]=e&&u?3:e?2:u?1:0;}}}int idx(int a,int ta,int b,int tb)const{return ((a*m+ta)*m+b)*m+tb;}int get(int a,int ta,int b,int tb)const{return d[idx(a,ta,b,tb)];}};
uint64_t enc(const array<uint8_t,9>&r,int m){uint64_t x=0;for(int i=0;i<m;i++)x=(x<<4)|r[i];return x;}
array<uint8_t,9> sw(const array<uint8_t,9>&r,int m,array<int,3>s){array<int,3>c{};int f=0,u=min({s[0],s[1],s[2]});for(int k=0;k<m;k++){if(u==s[0]||u==s[1]||u==s[2])c[f++]=u;u=r[u];}auto o=r;o[c[0]]=r[c[1]];o[c[1]]=r[c[2]];o[c[2]]=r[c[0]];return o;}
int main(){const int m=9;Rel R(m);vector<array<uint8_t,9>>cy;vector<int>tail(m-1);iota(tail.begin(),tail.end(),1);do{array<uint8_t,9>ord{},r{};ord[0]=0;for(int i=1;i<m;i++)ord[i]=tail[i-1];for(int i=0;i<m;i++)r[ord[i]]=ord[(i+1)%m];cy.push_back(r);}while(next_permutation(tail.begin(),tail.end()));unordered_map<uint64_t,int>ix;ix.reserve(cy.size()*2);for(int i=0;i<(int)cy.size();i++)ix[enc(cy[i],m)]=i;vector<array<int,3>>tr;for(int a=0;a<m;a++)for(int b=a+1;b<m;b++)for(int c=b+1;c<m;c++)tr.push_back({a,b,c});const int K=tr.size();
vector<array<int,84>>nei(cy.size());for(int i=0;i<(int)cy.size();i++)for(int t=0;t<K;t++)nei[i][t]=ix.at(enc(sw(cy[i],m,tr[t]),m));
vector<uint64_t>meetLo(K),meetHi(K);for(int t=0;t<K;t++)for(int s=0;s<K;s++){bool hit=false;for(int x:tr[t])for(int y:tr[s])if(x==y)hit=true;if(hit){if(s<64)meetLo[t]|=1ULL<<s;else meetHi[t]|=1ULL<<(s-64);}}
vector<int>off(cy.size()+1);vector<uint16_t>oris;oris.reserve(7000000);vector<uint64_t>flo,fhi;vector<uint16_t>atom;flo.reserve(7000000);fhi.reserve(7000000);atom.reserve(7000000);long long valid=0;int satcycles=0;
for(int ci=0;ci<(int)cy.size();ci++){off[ci]=oris.size();vector<array<int,3>>edges;bool imp=false;for(int a=0;a<m;a++)for(int b=a+1;b<m;b++){int v=R.get(a,cy[ci][a],b,cy[ci][b]);if(v==3)imp=true;else if(v)edges.push_back({a,b,v==1?0:1});}if(imp)continue;array<uint8_t,84>badpat{};array<array<uint8_t,8>,84>ac{};for(int ti=0;ti<K;ti++){auto T=tr[ti];uint8_t mask=0;for(int p=0;p<8;p++){int q=triplecount(m,T[0],cy[ci][T[0]],(p>>0)&1,T[1],cy[ci][T[1]],(p>>1)&1,T[2],cy[ci][T[2]],(p>>2)&1);ac[ti][p]=q;if(q)mask|=1u<<p;}badpat[ti]=mask;}int before=oris.size();for(int o=0;o<(1<<m);o++){bool ok=true;for(auto e:edges)if(((((o>>e[0])&1)^((o>>e[1])&1))!=e[2])){ok=false;break;}if(!ok)continue;uint64_t lo=0,hi=0;int at=0;for(int ti=0;ti<K;ti++){auto T=tr[ti];int p=((o>>T[0])&1)|(((o>>T[1])&1)<<1)|(((o>>T[2])&1)<<2);at+=ac[ti][p];if((badpat[ti]>>p)&1){if(ti<64)lo|=1ULL<<ti;else hi|=1ULL<<(ti-64);}}oris.push_back(o);flo.push_back(lo);fhi.push_back(hi);atom.push_back(at);if(!(lo|hi))valid++;}if((int)oris.size()>before)satcycles++;}
off[cy.size()]=oris.size();vector<int8_t>dist(oris.size(),-1),cmin(cy.size(),-1);deque<int>q;for(int ci=0;ci<(int)cy.size();ci++)for(int id=off[ci];id<off[ci+1];id++)if(!(flo[id]|fhi[id])){dist[id]=0;if(cmin[ci]<0){cmin[ci]=0;q.push_back(ci);}}
while(!q.empty()){int eta=q.front();q.pop_front();int nd=cmin[eta]+1;for(int t=0;t<K;t++){int rho=nei[eta][t];bool any=false;for(int id=off[rho];id<off[rho+1];id++)if(dist[id]<0&&((flo[id]&meetLo[t])||(fhi[id]&meetHi[t]))){dist[id]=nd;any=true;}if(any&&cmin[rho]<0){cmin[rho]=nd;q.push_back(rho);}}}
array<long long,16>dd{};long long un=0;for(auto d:dist)if(d<0)un++;else dd[d]++;vector<int>minSup(cy.size(),999),minAtom(cy.size(),9999);for(int ci=0;ci<(int)cy.size();ci++)for(int id=off[ci];id<off[ci+1];id++){int sp=__builtin_popcountll(flo[id])+__builtin_popcountll(fhi[id]);minSup[ci]=min(minSup[ci],sp);minAtom[ci]=min(minAtom[ci],(int)atom[id]);}
vector<pair<int,int>>ownerMasks;for(int mask=1;mask<(1<<m);mask++)ownerMasks.push_back({__builtin_popcount((unsigned)mask),mask});sort(ownerMasks.begin(),ownerMasks.end());vector<uint64_t>disLo(1<<m),disHi(1<<m);for(int mask=1;mask<(1<<m);mask++)for(int ti=0;ti<K;ti++){bool hit=false;for(int x:tr[ti])if((mask>>x)&1)hit=true;if(!hit){if(ti<64)disLo[mask]|=1ULL<<ti;else disHi[mask]|=1ULL<<(ti-64);}}
map<int,long long>d4Support,d4Cover;int d4MaxSupport=0,d4MaxCover=0;for(int id=0;id<(int)dist.size();id++)if(dist[id]==4){int sp=__builtin_popcountll(flo[id])+__builtin_popcountll(fhi[id]);d4Support[sp]++;d4MaxSupport=max(d4MaxSupport,sp);int cv=0;for(auto [k,mask]:ownerMasks)if(((flo[id]&disLo[mask])|(fhi[id]&disHi[mask]))==0){cv=k;break;}d4Cover[cv]++;d4MaxCover=max(d4MaxCover,cv);}
vector<int>oriToId(cy.size()*(1<<m),-1);for(int ci=0;ci<(int)cy.size();ci++)for(int id=off[ci];id<off[ci+1];id++)oriToId[ci*(1<<m)+oris[id]]=id;vector<vector<int>>cadj(cy.size());for(int ci=0;ci<(int)cy.size();ci++){for(int t=0;t<K;t++){bool ok=false;for(int id=off[ci];id<off[ci+1];id++)if((flo[id]&meetLo[t])||(fhi[id]&meetHi[t])){ok=true;break;}if(ok&&off[nei[ci][t]]<off[nei[ci][t]+1])cadj[ci].push_back(nei[ci][t]);}sort(cadj[ci].begin(),cadj[ci].end());cadj[ci].erase(unique(cadj[ci].begin(),cadj[ci].end()),cadj[ci].end());}
long long supFail=0,atomFail=0,bothFail=0,d4BothFail=0;array<long long,16>supFailD{},atomFailD{};map<int,long long>hardSup,hardAtom,hardCover;map<vector<int>,long long>hardDeg;set<int>hardCycles;long long hardPairs=0;vector<int>hardIds;
for(int ci=0;ci<(int)cy.size();ci++)for(int id=off[ci];id<off[ci+1];id++){if(!(flo[id]|fhi[id]))continue;int sp=__builtin_popcountll(flo[id])+__builtin_popcountll(fhi[id]),at=atom[id];bool sd=false,ad=false;for(int t=0;t<K;t++)if((flo[id]&meetLo[t])||(fhi[id]&meetHi[t])){int eta=nei[ci][t];if(minSup[eta]<sp)sd=true;if(minAtom[eta]<at)ad=true;}if(!sd){supFail++;supFailD[dist[id]]++;}if(!ad){atomFail++;atomFailD[dist[id]]++;}if(!sd&&!ad){bothFail++;if(dist[id]==4){d4BothFail++;hardIds.push_back(id);hardCycles.insert(ci);hardSup[sp]++;hardAtom[at]++;int cv=0;for(auto [k,mask]:ownerMasks)if(((flo[id]&disLo[mask])|(fhi[id]&disHi[mask]))==0){cv=k;break;}hardCover[cv]++;vector<int>deg(m);for(int ti=0;ti<K;ti++){bool on=ti<64?((flo[id]>>ti)&1):((fhi[id]>>(ti-64))&1);if(on)for(int x:tr[ti])deg[x]++;}sort(deg.rbegin(),deg.rend());hardDeg[deg]++;int comp=oriToId[ci*(1<<m)+(oris[id]^((1<<m)-1))];if(comp>id&&dist[comp]==4)hardPairs++;}}}
vector<int>seen(cy.size());int stamp=0;map<int,long long>lowerA,lowerS;auto lower=[&](int id,bool useA){int ci=upper_bound(off.begin(),off.end(),id)-off.begin()-1,threshold=useA?atom[id]:(__builtin_popcountll(flo[id])+__builtin_popcountll(fhi[id]));deque<pair<int,int>>qq;++stamp;for(int t=0;t<K;t++)if((flo[id]&meetLo[t])||(fhi[id]&meetHi[t])){int eta=nei[ci][t];if(seen[eta]!=stamp){seen[eta]=stamp;qq.push_back({eta,1});}}while(!qq.empty()){auto [u,d]=qq.front();qq.pop_front();int val=useA?minAtom[u]:minSup[u];if(val<threshold)return d;for(int v:cadj[u])if(seen[v]!=stamp){seen[v]=stamp;qq.push_back({v,d+1});}}return -1;};for(int id:hardIds){lowerA[lower(id,true)]++;lowerS[lower(id,false)]++;}
bool verified=satcycles==31688&&oris.size()==6727728&&valid==8&&un==0&&dd[0]==8&&dd[1]==59008&&dd[2]==1317376&&dd[3]==4873296&&dd[4]==478040&&d4MaxSupport==43&&d4MaxCover==5&&d4Cover==map<int,long long>{{1,588},{2,58772},{3,318892},{4,97848},{5,1940}}&&supFail==2160&&atomFail==2148&&bothFail==2104&&d4BothFail==68&&hardSup==map<int,long long>{{1,8},{2,56},{3,4}}&&hardAtom==map<int,long long>{{4,8},{8,56},{12,4}}&&hardCover==map<int,long long>{{1,40},{2,28}}&&hardCycles.size()==22&&hardPairs==34&&lowerA==map<int,long long>{{2,60},{4,8}}&&lowerS==map<int,long long>{{2,60},{4,8}};if(!verified){cerr<<"verification mismatch\n";return 1;}
cout<<"{\n  \"m\":9,\n  \"hamilton_cycles\":"<<cy.size()<<",\n  \"parity_satisfiable_cycles\":"<<satcycles<<",\n  \"clean_signed_states\":"<<oris.size()<<",\n  \"valid_states\":"<<valid<<",\n  \"unreached_states\":"<<un<<",\n  \"distance_distribution\":{\"0\":"<<dd[0]<<",\"1\":"<<dd[1]<<",\"2\":"<<dd[2]<<",\"3\":"<<dd[3]<<",\"4\":"<<dd[4]<<"},\n  \"distance_four_maximum_supports\":"<<d4MaxSupport<<",\n  \"distance_four_maximum_owner_cover\":"<<d4MaxCover<<",\n  \"support_count_local_minima\":"<<supFail<<",\n  \"atomic_count_local_minima\":"<<atomFail<<",\n  \"joint_support_atomic_local_minima\":"<<bothFail<<",\n  \"distance_four_joint_local_minima\":"<<d4BothFail<<",\n  \"distance_four_joint_cycles\":"<<hardCycles.size()<<",\n  \"distance_four_joint_complement_pairs\":"<<hardPairs<<",\n  \"verified\":true,\n  \"asymptotic_theorem_proved\":false\n}\n";
}
