#!/usr/bin/env python3
from collections import Counter
from itertools import combinations, combinations_with_replacement, permutations

SOURCE = (
    (2, 1, 1, 0),
    (0, 2, 1, 1),
    (1, 0, 2, 1),
    (1, 1, 0, 2),
)
PERMUTATIONS = tuple(permutations(range(4)))

def collinear(a, b, c):
    return (b[0] - a[0]) * (c[1] - a[1]) == (b[1] - a[1]) * (c[0] - a[0])

def legal(permutation):
    points = tuple((row, permutation[row]) for row in range(4))
    return all(not collinear(*triple) for triple in combinations(points, 3))

def layer_matrix(layers):
    result = [[0] * 4 for _ in range(4)]
    for layer in layers:
        for row, column in enumerate(layer):
            result[row][column] += 1
    return tuple(tuple(row) for row in result)

def distance(left, right):
    return sum(abs(left[row][column] - right[row][column]) for row in range(4) for column in range(4))

def elementary_swaps(matrix):
    records = []
    for row_a, row_b in combinations(range(4), 2):
        for col_a, col_b in combinations(range(4), 2):
            for orientation in (0, 1):
                removed = ((row_a, col_a), (row_b, col_b)) if orientation == 0 else ((row_a, col_b), (row_b, col_a))
                added = ((row_a, col_b), (row_b, col_a)) if orientation == 0 else ((row_a, col_a), (row_b, col_b))
                if not all(matrix[row][column] > 0 for row, column in removed):
                    continue
                candidate = [list(row) for row in matrix]
                for row, column in removed:
                    candidate[row][column] -= 1
                for row, column in added:
                    candidate[row][column] += 1
                records.append((tuple(tuple(row) for row in candidate), removed, added))
    return tuple(records)

legal_layers = tuple(permutation for permutation in PERMUTATIONS if legal(permutation))
assert len(legal_layers) == 18
legal_matrices = {}
for indices in combinations_with_replacement(range(len(legal_layers)), 4):
    matrix = layer_matrix(tuple(legal_layers[index] for index in indices))
    legal_matrices[matrix] = legal_matrices.get(matrix, 0) + 1
assert len(legal_matrices) == 4475
minimum_distance = min(distance(SOURCE, matrix) for matrix in legal_matrices)
nearest = tuple(matrix for matrix in legal_matrices if distance(SOURCE, matrix) == minimum_distance)
assert minimum_distance == 6 and len(nearest) == 8

paths = []
for intermediate, removed_a, added_a in elementary_swaps(SOURCE):
    for target, removed_b, added_b in elementary_swaps(intermediate):
        if target in nearest:
            paths.append((target, intermediate, removed_a, added_a, removed_b, added_b))
assert len(paths) == 48
assert Counter(record[0] for record in paths) == Counter({target: 6 for target in nearest})
assert len({record[1] for record in paths}) == 20
assert all(record[1] not in legal_matrices for record in paths)
assert all(target not in {candidate for candidate, _, _ in elementary_swaps(SOURCE)} for target in nearest)

print({
    "nearest_legal_targets": len(nearest),
    "minimum_entrywise_l1_distance": minimum_distance,
    "elementary_conservative_swaps_per_target": 2,
    "ordered_two_swap_paths": len(paths),
    "ordered_paths_per_target": 6,
    "distinct_intermediate_matrices": len({record[1] for record in paths}),
    "geometrically_legal_intermediates": 0,
    "conclusion": "the threshold three-cycle targets are algebraically generated by two 2x2 swaps, but the swaps must be treated atomically because every intermediate is illegal",
    "remaining_gap": "no prime-patching source operation realizes the two-swap compound without exposing its illegal intermediate",
    "evidence_level": "exact_two_swap_threshold_generation",
    "status": "passed",
})
