#include <bits/stdc++.h>
using namespace std;using S=array<uint8_t,60>;struct M{uint8_t l,i,j;};
struct Board{vector<vector<int>>lines,cl;vector<int>pl;Board(){cl.resize(900);pl.assign(810000,-1);for(int dx=0;dx<=29;dx++)for(int dy=-29;dy<=29;dy++){if(dx==0&&dy!=1)continue;if(!dx&&!dy)continue;if(gcd(abs(dx),abs(dy))!=1)continue;for(int x=1;x<=30;x++)for(int y=1;y<=30;y++){int px=x-dx,py=y-dy;if(px>=1&&px<=30&&py>=1&&py<=30)continue;vector<int>v;for(int a=x,b=y;a>=1&&a<=30&&b>=1&&b<=30;a+=dx,b+=dy)v.push_back((a-1)*30+b-1);if(v.size()<3)continue;int id=lines.size();lines.push_back(v);for(int a:v)cl[a].push_back(id);for(int i=0;i<(int)v.size();i++)for(int j=i+1;j<(int)v.size();j++)pl[v[i]*900+v[j]]=pl[v[j]*900+v[i]]=id;}}assert(lines.size()==34270);cerr<<"lines "<<lines.size()<<"\n";}}G;
S start(){vector<int>r={14,15,9,18,8,25,29,3,4,13,19,2,23,28,1,12,7,24,6,17,11,26,30,5,22,27,20,16,21,10},b={18,10,24,6,14,15,23,20,25,1,9,4,7,29,30,27,28,19,2,5,3,13,21,11,8,26,12,22,17,16};S s{};for(int i=0;i<30;i++)s[i]=r[i],s[30+i]=b[i];return s;}
bool legal(S const&s,M m){int o=30*m.l,q=30*(1-m.l);return s[o+m.j]!=s[q+m.i]&&s[o+m.i]!=s[q+m.j];}S apply(S s,M m){swap(s[30*m.l+m.i],s[30*m.l+m.j]);return s;}bool co(int a,int b,int c){if(a==b||a==c||b==c)return false;int x1=a/30,y1=a%30,x2=b/30,y2=b%30,x3=c/30,y3=c%30;return 1LL*(x2-x1)*(y3-y1)==1LL*(y2-y1)*(x3-x1);}
struct Eval{bool sel[900];vector<uint8_t>lc;int af[900];Eval(S const&s):lc(G.lines.size()){memset(sel,0,sizeof sel);for(int l=0;l<2;l++)for(int i=0;i<30;i++)sel[i*30+s[30*l+i]-1]=1;for(int z=0;z<900;z++)if(sel[z])for(int id:G.cl[z])lc[id]++;for(int z=0;z<900;z++){int v=0;for(int id:G.cl[z]){int c=lc[id]-sel[z];v+=c*(c-1)/2;}af[z]=v;}}int K(int a,int b)const{int id=G.pl[a*900+b];return id<0?0:lc[id]-sel[a]-sel[b];}int np(S const&s,int p,M m)const{int o=30*m.l,a=m.i*30+s[o+m.i]-1,b=m.j*30+s[o+m.j]-1,c=m.i*30+s[o+m.j]-1,d=m.j*30+s[o+m.i]-1;int old=af[a]+af[b]-K(a,b),nc=af[c]-K(c,a)-K(c,b)+co(c,a,b),nd=af[d]-K(d,a)-K(d,b)+co(d,a,b),cd=K(c,d)-co(c,d,a)-co(c,d,b);return p-old+nc+nd+cd;}};
uint64_t H(S const&s){uint64_t h=0x9e3779b97f4a7c15ULL;for(auto x:s){h^=x+0x9e3779b9+(h<<6)+(h>>2);h*=0xbf58476d1ce4e5b9ULL;}return h^(h>>31);}struct N{S s;int pa;M m;uint8_t p;};
struct Tab{vector<int>t;size_t used=0;deque<N>*n;Tab(size_t z,deque<N>*p):t(z,-1),n(p){}void grow(){vector<int>o=move(t);t.assign(o.size()*2,-1);used=0;for(int id:o)if(id>=0)put((*n)[id].s,id);}pair<int,bool> put(S const&s,int id){if((used+1)*10>t.size()*7)grow();size_t m=t.size()-1,i=H(s)&m;while(1){int x=t[i];if(x<0){t[i]=id;used++;return{id,true};}if((*n)[x].s==s)return{x,false};i=(i+1)&m;}}};
string W(M m){return string(m.l?"b:":"r:")+to_string(m.i+1)+","+to_string(m.j+1);}int main(){S st=start();vector<M>mv;for(int l=0;l<2;l++)for(int i=0;i<30;i++)for(int j=i+1;j<30;j++)mv.push_back({(uint8_t)l,(uint8_t)i,(uint8_t)j});deque<N>ns;ns.push_back({st,-1,{0,0,0},3});Tab tab(1u<<22,&ns);tab.put(st,0);size_t pos=0;while(pos<ns.size()){N cur=ns[pos];Eval ev(cur.s);for(auto m:mv){if(!legal(cur.s,m))continue;int p=ev.np(cur.s,cur.p,m);if(p>9)continue;S s=apply(cur.s,m);int id=ns.size();auto [old,added]=tab.put(s,id);if(!added)continue;ns.push_back({s,(int)pos,m,(uint8_t)p});if(p<3){vector<M>path;for(int x=id;ns[x].pa>=0;x=ns[x].pa)path.push_back(ns[x].m);reverse(path.begin(),path.end());cout<<"moves "<<path.size()<<" max 9 expanded "<<pos+1<<" seen "<<ns.size()<<"\n"<<3;S u=st;int q=3;for(auto x:path){Eval e(u);q=e.np(u,q,x);u=apply(u,x);cout<<" "<<W(x)<<":"<<q;}cout<<"\n";return 0;}}pos++;if(pos%100000==0)cerr<<"pos "<<pos<<" states "<<ns.size()<<" q "<<ns.size()-pos<<" table "<<tab.t.size()<<"\n";}cerr<<"EXHAUSTED states "<<ns.size()<<"\n";cout<<"exhausted "<<ns.size()<<"\n";}
