#!/usr/bin/env python3
"""Replay the exact remaining radius-two coordinate census for class (5,2)."""
from __future__ import annotations

import argparse
import re
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "scripts" / "search_product_side_seven_radius_two_support.cpp"

# Intervals are inclusive and use the deterministic lexicographic selector order
# generated by the exact C++ search program.
CASES: dict[int, list[tuple[int, int, int]]] = {
    20: [
        (1, 677, 316_808_398),
        (678, 1_354, 401_284_589),
        (1_355, 2_031, 489_020_677),
        (2_032, 2_708, 572_742_409),
        (2_709, 3_385, 510_382_544),
        (3_386, 4_062, 533_140_022),
        (4_063, 4_739, 573_035_141),
        (4_740, 5_416, 582_252_474),
        (5_417, 6_093, 649_854_512),
        (6_094, 6_762, 795_289_448),
    ],
    22: [
        (1, 591, 299_064_507),
        (592, 1_182, 423_592_289),
        (1_183, 1_773, 489_300_346),
        (1_774, 2_364, 432_845_495),
        (2_365, 2_955, 490_193_167),
        (2_956, 3_544, 632_135_006),
    ],
    24: [
        (1, 386, 221_467_808),
        (387, 772, 320_176_946),
        (773, 1_158, 283_375_514),
        (1_159, 1_544, 329_941_224),
        (1_545, 1_930, 380_966_043),
    ],
    26: [(1, 388, 301_158_609), (389, 776, 330_241_135)],
    28: [(1, 288, 229_218_191)],
    30: [(1, 56, 34_757_139)],
    32: [(1, 45, 30_055_392)],
    34: [(1, 8, 4_827_528)],
    36: [(1, 4, 2_750_582)],
    40: [(1, 1, 508_527)],
}

EXPECTED_COUNTS = {
    20: 6_762,
    22: 3_544,
    24: 1_930,
    26: 776,
    28: 288,
    30: 56,
    32: 45,
    34: 8,
    36: 4,
    40: 1,
}

LINE = re.compile(
    r"cycle52 range=(\d+)-(\d+) done=(\d+) nodes=(\d+) NO"
)
LAYER = re.compile(r"cycle52 support=(\d+) layer=(\d+)")


def compile_solver(binary: Path) -> None:
    subprocess.run(
        ["g++", "-O3", "-std=c++17", str(SOURCE), "-o", str(binary)],
        check=True,
    )


def run_case(binary: Path, support: int, first: int, last: int, nodes: int) -> None:
    completed = subprocess.run(
        [str(binary), "cycle52", str(support), str(first), str(last)],
        check=True,
        capture_output=True,
        text=True,
    )
    if "FOUND" in completed.stdout:
        raise AssertionError(completed.stdout)
    layer_match = LAYER.search(completed.stderr)
    assert layer_match, completed.stderr
    assert int(layer_match.group(1)) == support
    assert int(layer_match.group(2)) == EXPECTED_COUNTS[support]
    match = LINE.fullmatch(completed.stdout.strip())
    assert match, completed.stdout
    got_first, got_last, done, got_nodes = map(int, match.groups())
    assert (got_first, got_last) == (first, last)
    assert done == last - first + 1
    assert got_nodes == nodes, (support, first, last, got_nodes, nodes)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--support",
        type=int,
        choices=sorted(CASES),
        help="Replay one support only; default replays every remaining support.",
    )
    args = parser.parse_args()

    supports = [args.support] if args.support is not None else sorted(CASES)
    with tempfile.TemporaryDirectory() as temporary:
        binary = Path(temporary) / "side7_cycle52_radius2"
        compile_solver(binary)
        grand_count = 0
        grand_nodes = 0
        for support in supports:
            count = 0
            nodes = 0
            for first, last, expected_nodes in CASES[support]:
                run_case(binary, support, first, last, expected_nodes)
                count += last - first + 1
                nodes += expected_nodes
            assert count == EXPECTED_COUNTS[support]
            grand_count += count
            grand_nodes += nodes
            print(f"support={support}: selectors={count}, nodes={nodes} PASS")

    if args.support is None:
        assert grand_count == 13_414
        assert grand_nodes == 10_660_385_662
        # Add the already-certified supports 8--18.
        assert grand_count + 13_136 == 26_550
        assert grand_nodes + 9_694_512_074 == 20_354_897_736
        print("PX565--PX569 complete (5,2) radius-two audit: PASS")


if __name__ == "__main__":
    main()
