#include <bits/stdc++.h>
#include <omp.h>
using namespace std;
struct L{int a,b,c;bool operator==(L const&o)const{return a==o.a&&b==o.b&&c==o.c;}};struct H{size_t operator()(L const&x)const noexcept{return ((uint64_t)(x.a+100)<<42)^((uint64_t)(x.b+100)<<32)^(uint32_t)(x.c+100000);}};
vector<int>pl;int C2[61],C3[61],INV[1771],NL;
L canon(int x1,int y1,int x2,int y2){int A=y2-y1,B=x1-x2,C=A*x1+B*y1,g=gcd(abs(A),gcd(abs(B),abs(C)));if(g)A/=g,B/=g,C/=g;if(A<0||(A==0&&B<0))A=-A,B=-B,C=-C;return{A,B,C};}
void init(){unordered_map<L,int,H>m;m.reserve(240000);pl.assign(810000,-1);int z=0;for(int u=0;u<900;u++)for(int v=u+1;v<900;v++){auto q=canon(u/30,u%30,v/30,v%30);auto[it,n]=m.emplace(q,z);if(n)z++;pl[u*900+v]=pl[v*900+u]=it->second;}NL=z;for(int k=0;k<=60;k++){C2[k]=k*(k-1)/2;C3[k]=k*(k-1)*(k-2)/6;INV[C2[k]]=k;}cerr<<"lines="<<NL<<"\n";}
struct Job{vector<unsigned char>re,be;};
void combs(const vector<int>&E,int need,int at,vector<unsigned char>&cur,vector<vector<unsigned char>>&out){if((int)cur.size()==need){out.push_back(cur);return;}for(int i=at;i+(need-(int)cur.size())<=(int)E.size();i++){cur.push_back(E[i]);combs(E,need,i+1,cur,out);cur.pop_back();}}
struct Worker{vector<int>mark,freq,paircnt,touched,ids;int stamp=1,pot=0;vector<int>cells,R,B,rv,bv;array<unsigned char,30>rass{},bass{},rused{},bused{};long long nodes=0,leaves=0;Worker():mark(NL),freq(NL),paircnt(NL){touched.reserve(1800);ids.reserve(60);cells.reserve(60);}void clear(){for(int id:touched)paircnt[id]=0;touched.clear();cells.clear();R.clear();B.clear();rv.clear();bv.clear();fill(rass.begin(),rass.end(),0);fill(bass.begin(),bass.end(),0);fill(rused.begin(),rused.end(),0);fill(bused.begin(),bused.end(),0);pot=0;}bool add(int cell){if(++stamp==INT_MAX){fill(mark.begin(),mark.end(),0);stamp=1;}ids.clear();for(int q:cells){int id=pl[cell*900+q];if(mark[id]!=stamp){mark[id]=stamp;freq[id]=0;ids.push_back(id);}freq[id]++;}int d=0;for(int id:ids)d+=C2[freq[id]];if(pot+d>2)return false;pot+=d;cells.push_back(cell);return true;}void rem(int op){cells.pop_back();pot=op;}bool build(const Job&j,const vector<int>&r0,const vector<int>&b0,const vector<int>&RB,const vector<int>&BB){clear();R=RB;B=BB;for(auto x:j.re)R.push_back(x);for(auto x:j.be)B.push_back(x);array<unsigned char,30>rm{},bm{};for(int x:R)rm[x]=1;for(int x:B)bm[x]=1;for(int i=0;i<30;i++){if(!rm[i]){rass[i]=r0[i];cells.push_back(i*30+r0[i]-1);}if(!bm[i]){bass[i]=b0[i];cells.push_back(i*30+b0[i]-1);}}for(int i=0;i<(int)cells.size();i++)for(int q=0;q<i;q++){int id=pl[cells[i]*900+cells[q]];if(paircnt[id]++==0)touched.push_back(id);}for(int id:touched)pot+=C3[INV[paircnt[id]]];if(pot>2)return false;for(int x:R)rv.push_back(r0[x]);for(int x:B)bv.push_back(b0[x]);return true;}int delta_cell(int cell){if(++stamp==INT_MAX){fill(mark.begin(),mark.end(),0);stamp=1;}ids.clear();for(int q:cells){int id=pl[cell*900+q];if(mark[id]!=stamp){mark[id]=stamp;freq[id]=0;ids.push_back(id);}freq[id]++;}int d=0;for(int id:ids)d+=C2[freq[id]];return d;}bool dfs(int d,vector<pair<int,int>>&ord,vector<int>&or_,vector<int>&ob){nodes++;if(d==(int)ord.size()){leaves++;or_.assign(rass.begin(),rass.end());ob.assign(bass.begin(),bass.end());return true;}int best=d,bn=INT_MAX;for(int t=d;t<(int)ord.size();t++){auto[l,row]=ord[t];auto&vs=l?bv:rv;auto&us=l?bused:rused;auto&op=l?rass:bass;int n=0;for(int k=0;k<(int)vs.size();k++){int y=vs[k];if(us[k]||(op[row]&&op[row]==y))continue;if(pot+delta_cell(row*30+y-1)<=2)n++;}if(n<bn){bn=n;best=t;if(n==0)break;}}if(bn==0)return false;swap(ord[d],ord[best]);auto[l,row]=ord[d];auto&vs=l?bv:rv;auto&us=l?bused:rused;auto&as=l?bass:rass;auto&op=l?rass:bass;vector<pair<int,int>>cand;for(int k=0;k<(int)vs.size();k++){int y=vs[k];if(us[k]||(op[row]&&op[row]==y))continue;int dd=delta_cell(row*30+y-1);if(pot+dd<=2)cand.push_back({dd,k});}sort(cand.begin(),cand.end());for(auto[dd,k]:cand){int y=vs[k],old=pot;if(!add(row*30+y-1))continue;us[k]=1;as[row]=y;if(dfs(d+1,ord,or_,ob))return true;as[row]=0;us[k]=0;rem(old);}swap(ord[d],ord[best]);return false;}};
int main(int argc,char**argv){init();int Kextra=argc>1?atoi(argv[1]):4,filter=argc>2?atoi(argv[2]):-1;vector<int>r0={12,15,24,9,27,20,4,17,28,29,6,2,8,13,1,18,7,19,23,11,26,30,10,5,14,3,21,22,25,16},b0={17,10,21,22,7,15,8,28,25,13,9,4,20,26,30,12,27,24,29,23,14,1,2,11,18,6,3,16,5,19},RB={13,15,19,22},BB={8,13,17,19,28},RE,BE;for(int i=0;i<30;i++){if(find(RB.begin(),RB.end(),i)==RB.end())RE.push_back(i);if(find(BB.begin(),BB.end(),i)==BB.end())BE.push_back(i);}vector<Job>jobs;for(int nr=0;nr<=Kextra;nr++){if(filter>=0&&nr!=filter)continue;int nb=Kextra-nr;vector<vector<unsigned char>>cr,cb;vector<unsigned char>tmp;combs(RE,nr,0,tmp,cr);tmp.clear();combs(BE,nb,0,tmp,cb);for(auto&r:cr)for(auto&b:cb)jobs.push_back({r,b});}cerr<<"K="<<Kextra<<" filter="<<filter<<" jobs="<<jobs.size()<<"\n";atomic<bool>found(false);atomic<long long>done(0),nodes(0),leaves(0);mutex mu;vector<int>solR,solB;Job sol;auto st=chrono::steady_clock::now();
#pragma omp parallel num_threads(5)
{Worker w;
#pragma omp for schedule(dynamic,1)
for(long long ji=0;ji<(long long)jobs.size();ji++){if(found.load())continue;auto&j=jobs[ji];if(!w.build(j,r0,b0,RB,BB)){done++;continue;}vector<pair<int,int>>ord;for(int x:w.R)ord.push_back({0,x});for(int x:w.B)ord.push_back({1,x});stable_sort(ord.begin(),ord.end(),[&](auto a,auto b){int oa=a.first?w.rass[a.second]:w.bass[a.second],ob=b.first?w.rass[b.second]:w.bass[b.second];return(oa!=0)>(ob!=0);});vector<int>rr,bb;if(w.dfs(0,ord,rr,bb)){lock_guard<mutex>g(mu);if(!found.exchange(true)){solR=rr;solB=bb;sol=j;}}done++;nodes+=w.nodes;leaves+=w.leaves;w.nodes=w.leaves=0;}}
auto sec=chrono::duration<double>(chrono::steady_clock::now()-st).count();cerr<<"DONE jobs="<<done<<" nodes="<<nodes<<" leaves="<<leaves<<" found="<<found<<" sec="<<sec<<"\n";if(found){cerr<<"unexpected potential-at-most-two endpoint\n";return 1;}long long ej=-1,en=-1;if(Kextra==4){long long J[]={12650,59800,97500,65000,14950},N[]={163790,795777,1367436,966121,232546};if(filter<0){ej=249900;en=3525670;}else if(filter<=4){ej=J[filter];en=N[filter];}}else if(Kextra==5){long long J[]={53130,328900,747500,780000,373750,65780},N[]={757086,4839909,11730921,13237666,6801838,1246608};if(filter<0){ej=2349060;en=38614028;}else if(filter<=5){ej=J[filter];en=N[filter];}}else return 2;assert(ej>=0);assert((long long)jobs.size()==ej);assert(done==ej);assert(nodes==en);assert(leaves==0);cout<<"AC p31 exact support closure\n"<<"extra_rows: "<<Kextra<<"\n"<<"red_extra_distribution: "<<filter<<"\n"<<"support_choices: "<<jobs.size()<<"\n"<<"partial_states: "<<nodes<<"\n"<<"complete_potential_at_most_two_states: "<<leaves<<"\n";return 0;}
