#include <bits/stdc++.h>
#include <omp.h>
using namespace std;
struct L{int a,b,c;bool operator==(L const&o)const{return a==o.a&&b==o.b&&c==o.c;}};
struct H{size_t operator()(L const&x)const noexcept{return ((uint64_t)(x.a+100)<<42)^((uint64_t)(x.b+100)<<32)^(uint32_t)(x.c+100000);}};
vector<int>pl;int C3[61],K[1771];
L ca(int x1,int y1,int x2,int y2){int A=y2-y1,B=x1-x2,C=A*x1+B*y1,g=gcd(abs(A),gcd(abs(B),abs(C)));if(g)A/=g,B/=g,C/=g;if(A<0||(A==0&&B<0))A=-A,B=-B,C=-C;return{A,B,C};}
void init(){unordered_map<L,int,H>m;m.reserve(240000);pl.assign(810000,-1);int z=0;for(int u=0;u<900;u++)for(int v=u+1;v<900;v++){auto q=ca(u/30,u%30,v/30,v%30);auto[it,n]=m.emplace(q,z);if(n)z++;pl[u*900+v]=pl[v*900+u]=it->second;}for(int k=0;k<=60;k++)C3[k]=k*(k-1)*(k-2)/6,K[k*(k-1)/2]=k;cerr<<"lines="<<z<<"\n";}
struct W{vector<unsigned short>base,add;vector<int>mark,touch,baseTouch;int stamp=1,basePot=0;vector<int>fixed;W(int n):base(n),add(n),mark(n){touch.reserve(800);baseTouch.reserve(1200);}void prepare(vector<int>const&fixedCells){for(int id:baseTouch)base[id]=0;baseTouch.clear();fixed=fixedCells;for(int i=0;i<(int)fixed.size();i++)for(int j=i+1;j<(int)fixed.size();j++){int id=pl[fixed[i]*900+fixed[j]];if(base[id]++==0)baseTouch.push_back(id);}basePot=0;for(int id:baseTouch)basePot+=C3[K[base[id]]];}int pot(vector<int>const&moving){if(++stamp==INT_MAX){fill(mark.begin(),mark.end(),0);stamp=1;}touch.clear();auto inc=[&](int id){if(mark[id]!=stamp){mark[id]=stamp;add[id]=0;touch.push_back(id);}add[id]++;};for(int i=0;i<(int)moving.size();i++){int c=moving[i];for(int f:fixed)inc(pl[c*900+f]);for(int j=0;j<i;j++)inc(pl[c*900+moving[j]]);}int p=basePot;for(int id:touch){int a=base[id],t=a+add[id];p+=C3[K[t]]-C3[K[a]];}return p;}};
bool disj(vector<int>const&r,vector<int>const&b){for(int i=0;i<30;i++)if(r[i]==b[i])return false;return true;}
int main(int argc,char**argv){init();int lo=argc>1?atoi(argv[1]):0,hi=argc>2?atoi(argv[2]):650;vector<int>r0={12,15,24,9,27,20,4,17,28,29,6,2,8,13,1,18,7,19,23,11,26,30,10,5,14,3,21,22,25,16},b0={17,10,21,22,7,15,8,28,25,13,9,4,20,26,30,12,27,24,29,23,14,1,2,11,18,6,3,16,5,19};vector<int>RB={13,19,22,15},BB={8,28,13,17,19},RE,BE;for(int i=0;i<30;i++){if(find(RB.begin(),RB.end(),i)==RB.end())RE.push_back(i);if(find(BB.begin(),BB.end(),i)==BB.end())BE.push_back(i);}vector<pair<int,int>>jobs;for(int er:RE)for(int eb:BE)jobs.push_back({er,eb});hi=min<int>(hi,jobs.size());int nl=*max_element(pl.begin(),pl.end())+1,T=min(5,omp_get_max_threads());vector<unique_ptr<W>>ws;for(int t=0;t<T;t++)ws.emplace_back(make_unique<W>(nl));atomic<int>found(0);mutex mu;vector<int>bestR,bestB;int best=3,bestEr=-1,bestEb=-1;atomic<long long>checked(0),valid(0);auto st=chrono::steady_clock::now();
#pragma omp parallel for num_threads(5) schedule(dynamic,1)
for(int z=lo;z<hi;z++){if(found.load())continue;int tid=omp_get_thread_num();auto&w=*ws[tid];auto[er,eb]=jobs[z];vector<int>R=RB,B=BB;R.push_back(er);B.push_back(eb);array<unsigned char,30>rm{},bm{};for(int x:R)rm[x]=1;for(int x:B)bm[x]=1;vector<int>fixed;for(int i=0;i<30;i++){if(!rm[i])fixed.push_back(i*30+r0[i]-1);if(!bm[i])fixed.push_back(i*30+b0[i]-1);}w.prepare(fixed);vector<int>rv,bv0;for(int i:R)rv.push_back(r0[i]);for(int i:B)bv0.push_back(b0[i]);sort(rv.begin(),rv.end());long long lc=0,lv=0;int local=99;do{vector<int>r=r0;for(int k=0;k<5;k++)r[R[k]]=rv[k];auto bv=bv0;sort(bv.begin(),bv.end());do{if(found.load())break;vector<int>b=b0;for(int k=0;k<6;k++)b[B[k]]=bv[k];lc++;if(!disj(r,b))continue;lv++;vector<int>moving;moving.reserve(11);for(int x:R)moving.push_back(x*30+r[x]-1);for(int x:B)moving.push_back(x*30+b[x]-1);int p=w.pot(moving);local=min(local,p);if(p<3){lock_guard<mutex>g(mu);if(!found.exchange(1)){best=p;bestR=r;bestB=b;bestEr=er;bestEb=eb;cerr<<"FOUND job="<<z<<" er="<<er+1<<" eb="<<eb+1<<" p="<<p<<"\n";}break;}}while(next_permutation(bv.begin(),bv.end()));if(found.load())break;}while(next_permutation(rv.begin(),rv.end()));checked+=lc;valid+=lv;}
auto sec=chrono::duration<double>(chrono::steady_clock::now()-st).count();if(found){cerr<<"unexpected lower state\n";return 1;}assert(lo==0&&hi==(int)jobs.size());assert(jobs.size()==650);assert(checked==56160000);assert(valid==42195600);assert(best==3);cout<<"AC p31 support closure: one red and one blue extra\n"<<"jobs: "<<jobs.size()<<"\nassignments: "<<checked<<"\nvalid: "<<valid<<"\nminimum: "<<best<<"\nseconds: "<<sec<<"\n";return 0;}
