#include <bits/stdc++.h>
#include <omp.h>
using namespace std;
struct L{int a,b,c;bool operator==(L const&o)const{return a==o.a&&b==o.b&&c==o.c;}};struct H{size_t operator()(L const&x)const noexcept{return ((uint64_t)(x.a+100)<<42)^((uint64_t)(x.b+100)<<32)^(uint32_t)(x.c+100000);}};
vector<int> pl; int C2[61],C3[61],INV[1771],NL;
L canon(int x1,int y1,int x2,int y2){int A=y2-y1,B=x1-x2,C=A*x1+B*y1,g=gcd(abs(A),gcd(abs(B),abs(C)));if(g)A/=g,B/=g,C/=g;if(A<0||(A==0&&B<0))A=-A,B=-B,C=-C;return{A,B,C};}
void init(){unordered_map<L,int,H>m;m.reserve(240000);pl.assign(810000,-1);int z=0;for(int u=0;u<900;u++)for(int v=u+1;v<900;v++){auto q=canon(u/30,u%30,v/30,v%30);auto[it,n]=m.emplace(q,z);if(n)z++;pl[u*900+v]=pl[v*900+u]=it->second;}NL=z;for(int k=0;k<=60;k++){C2[k]=k*(k-1)/2;C3[k]=k*(k-1)*(k-2)/6;INV[C2[k]]=k;}cerr<<"lines="<<NL<<"\n";}
struct Job{array<unsigned char,3> re{},be{}; unsigned char nr=0,nb=0;};
struct Worker{vector<int>mark,freq,paircnt,touched,ids;int stamp=1,pot=0;vector<int>cells,R,B,rv,bv;array<unsigned char,30>rass{},bass{},rused{},bused{};long long nodes=0,leaves=0;Worker():mark(NL),freq(NL),paircnt(NL){touched.reserve(1800);ids.reserve(60);cells.reserve(60);}void clear(){for(int id:touched)paircnt[id]=0;touched.clear();cells.clear();fill(rass.begin(),rass.end(),0);fill(bass.begin(),bass.end(),0);fill(rused.begin(),rused.end(),0);fill(bused.begin(),bused.end(),0);pot=0;}bool add_cell(int cell){if(++stamp==INT_MAX){fill(mark.begin(),mark.end(),0);stamp=1;}ids.clear();for(int q:cells){int id=pl[cell*900+q];if(mark[id]!=stamp){mark[id]=stamp;freq[id]=0;ids.push_back(id);}freq[id]++;}int delta=0;for(int id:ids)delta+=C2[freq[id]];if(pot+delta>2)return false;pot+=delta;cells.push_back(cell);return true;}void remove_cell(int oldpot){cells.pop_back();pot=oldpot;}bool build(const Job&j,const vector<int>&r0,const vector<int>&b0,const vector<int>&RB,const vector<int>&BB){clear();R=RB;B=BB;for(int k=0;k<j.nr;k++)R.push_back(j.re[k]);for(int k=0;k<j.nb;k++)B.push_back(j.be[k]);array<unsigned char,30>rm{},bm{};for(int x:R)rm[x]=1;for(int x:B)bm[x]=1;for(int i=0;i<30;i++){if(!rm[i]){rass[i]=r0[i];cells.push_back(i*30+r0[i]-1);}if(!bm[i]){bass[i]=b0[i];cells.push_back(i*30+b0[i]-1);}}for(int i=0;i<(int)cells.size();i++)for(int k=0;k<i;k++){int id=pl[cells[i]*900+cells[k]];if(paircnt[id]++==0)touched.push_back(id);}pot=0;for(int id:touched)pot+=C3[INV[paircnt[id]]];if(pot>2)return false;rv.clear();bv.clear();for(int x:R)rv.push_back(r0[x]);for(int x:B)bv.push_back(b0[x]);return true;}bool dfs(int depth,vector<pair<int,int>>const&ord){nodes++;if(depth==(int)ord.size()){leaves++;return true;}auto[l,row]=ord[depth];auto&vals=l?bv:rv;auto&used=l?bused:rused;auto&ass=l?bass:rass;auto&opp=l?rass:bass;for(int k=0;k<(int)vals.size();k++){int y=vals[k];if(used[k])continue;if(opp[row]&&opp[row]==y)continue;int oldpot=pot;if(!add_cell(row*30+y-1))continue;used[k]=1;ass[row]=y;if(dfs(depth+1,ord))return true;ass[row]=0;used[k]=0;remove_cell(oldpot);}return false;}};
int main(int argc,char**argv){init();int filter=argc>1?atoi(argv[1]):-1;vector<int>r0={12,15,24,9,27,20,4,17,28,29,6,2,8,13,1,18,7,19,23,11,26,30,10,5,14,3,21,22,25,16},b0={17,10,21,22,7,15,8,28,25,13,9,4,20,26,30,12,27,24,29,23,14,1,2,11,18,6,3,16,5,19};vector<int>RB={13,15,19,22},BB={8,13,17,19,28},RE,BE;for(int i=0;i<30;i++){if(find(RB.begin(),RB.end(),i)==RB.end())RE.push_back(i);if(find(BB.begin(),BB.end(),i)==BB.end())BE.push_back(i);}vector<Job>jobs;for(int nr=0;nr<=3;nr++){int nb=3-nr;if(filter>=0&&nr!=filter)continue;if(nr==0){for(int a=0;a<25;a++)for(int b=a+1;b<25;b++)for(int c=b+1;c<25;c++){Job j;j.nb=3;j.be={(unsigned char)BE[a],(unsigned char)BE[b],(unsigned char)BE[c]};jobs.push_back(j);}}else if(nr==1){for(int r:RE)for(int a=0;a<25;a++)for(int b=a+1;b<25;b++){Job j;j.nr=1;j.nb=2;j.re[0]=r;j.be={(unsigned char)BE[a],(unsigned char)BE[b],0};jobs.push_back(j);}}else if(nr==2){for(int a=0;a<26;a++)for(int b=a+1;b<26;b++)for(int q:BE){Job j;j.nr=2;j.nb=1;j.re={(unsigned char)RE[a],(unsigned char)RE[b],0};j.be[0]=q;jobs.push_back(j);}}else{for(int a=0;a<26;a++)for(int b=a+1;b<26;b++)for(int c=b+1;c<26;c++){Job j;j.nr=3;j.re={(unsigned char)RE[a],(unsigned char)RE[b],(unsigned char)RE[c]};jobs.push_back(j);}}}cerr<<"jobs="<<jobs.size()<<" filter="<<filter<<"\n";atomic<bool>found(false);atomic<long long>done(0),nodes(0),leaves(0);auto st=chrono::steady_clock::now();
#pragma omp parallel num_threads(5)
{Worker w;
#pragma omp for schedule(dynamic,1)
for(long long ji=0;ji<(long long)jobs.size();ji++){if(found.load())continue;auto&j=jobs[ji];if(!w.build(j,r0,b0,RB,BB)){done++;continue;}vector<pair<int,int>>ord;for(int x:w.R)ord.push_back({0,x});for(int x:w.B)ord.push_back({1,x});stable_sort(ord.begin(),ord.end(),[&](auto a,auto b){int oa=a.first?w.rass[a.second]:w.bass[a.second],ob=b.first?w.rass[b.second]:w.bass[b.second];return(oa!=0)>(ob!=0);});if(w.dfs(0,ord))found=true;done++;nodes+=w.nodes;leaves+=w.leaves;w.nodes=w.leaves=0;}}
auto sec=chrono::duration<double>(chrono::steady_clock::now()-st).count();cerr<<"DONE jobs="<<done<<" nodes="<<nodes<<" leaves="<<leaves<<" found="<<found<<" sec="<<sec<<"\n";if(found){cerr<<"unexpected potential-at-most-two endpoint\n";return 1;}long long ej=0,en=0;if(filter<0){ej=20825;en=773961;}else if(filter==0){ej=2300;en=109579;}else if(filter==1){ej=7800;en=295821;}else if(filter==2){ej=8125;en=276343;}else if(filter==3){ej=2600;en=92218;}else return 2;assert((long long)jobs.size()==ej);assert(done==ej);assert(nodes==en);assert(leaves==0);cout<<"AC p31 exact support-three closure\n"<<"distribution_red_extras: "<<filter<<"\n"<<"support_choices: "<<jobs.size()<<"\n"<<"partial_states: "<<nodes<<"\n"<<"complete_potential_at_most_two_states: "<<leaves<<"\n";return 0;}
