#include <bits/stdc++.h>
using namespace std;
static int md(int x,int p){x%=p;if(x<0)x+=p;return x;}
struct E{int x,y,d,s;};
static E edge(int p,int x,int y){return {x,y,md(x-y,p),md(x+y,p)};}
static vector<int> pm(int p,int g){return {md(-g,p),g};}
static bool matching(const vector<E>& es){for(int part=0;part<4;part++){set<int> z;for(auto e:es){int v=part==0?e.x:part==1?e.y:part==2?e.d:e.s;if(!z.insert(v).second)return false;}}return true;}
static array<set<int>,4> vertices(const vector<E>&es){array<set<int>,4> out;for(auto e:es){out[0].insert(e.x);out[1].insert(e.y);out[2].insert(e.d);out[3].insert(e.s);}return out;}
static bool directN(int p,array<vector<int>,4> U){auto R=U[0],C=U[1],D=U[2],S=U[3];sort(R.begin(),R.end());sort(C.begin(),C.end());sort(D.begin(),D.end());sort(S.begin(),S.end());do{vector<int>d(R.size()),s(R.size());for(int i=0;i<(int)R.size();i++){d[i]=md(R[i]-C[i],p);s[i]=md(R[i]+C[i],p);}sort(d.begin(),d.end());sort(s.begin(),s.end());if(d==D&&s==S)return true;}while(next_permutation(C.begin(),C.end()));return false;}
static bool absorber2(int p,const array<vector<int>,4>&L){vector<E> ed;for(int x=0;x<p;x++)for(int y=0;y<p;y++){E e=edge(p,x,y);bool ok=1;int vv[4]={e.x,e.y,e.d,e.s};for(int j=0;j<4;j++)if(find(L[j].begin(),L[j].end(),vv[j])!=L[j].end())ok=0;if(ok)ed.push_back(e);}for(int i=0;i<(int)ed.size();i++)for(int k=i+1;k<(int)ed.size();k++){vector<E> m0={ed[i],ed[k]};if(!matching(m0))continue;array<vector<int>,4>U=L;int a[4]={ed[i].x,ed[i].y,ed[i].d,ed[i].s};int b[4]={ed[k].x,ed[k].y,ed[k].d,ed[k].s};bool distinct=true;for(int j=0;j<4;j++){U[j].push_back(a[j]);U[j].push_back(b[j]);sort(U[j].begin(),U[j].end());if(unique(U[j].begin(),U[j].end())!=U[j].end())distinct=false;}if(distinct&&directN(p,U))return true;}return false;}
struct W{int p,b,u,v;vector<pair<int,int>>m0,m1;};
static bool verify_witness(const W&w){array<vector<int>,4>L={pm(w.p,1),pm(w.p,w.b),pm(w.p,w.u),pm(w.p,w.v)};vector<E>M0,M1;for(auto [x,y]:w.m0)M0.push_back(edge(w.p,x,y));for(auto [x,y]:w.m1)M1.push_back(edge(w.p,x,y));if(!matching(M0)||!matching(M1))return false;auto A=vertices(M0),B=vertices(M1);for(int j=0;j<4;j++){set<int> want=A[j];want.insert(L[j].begin(),L[j].end());if(want!=B[j])return false;}return true;}
int main(){map<int,vector<array<int,3>>> expected={{7,{}},{11,{}},{13,{}},{17,{{1,6,6},{4,6,7},{4,7,6}}},{19,{{1,4,8},{1,8,4},{2,9,9},{9,5,5}}}};map<int,int> populations={{7,1},{11,4},{13,8},{17,19},{19,24}};for(auto &[p,exp]:expected){vector<array<int,3>>fail;int non=0;for(int b=1;b<=(p-1)/2;b++)for(int u=1;u<=(p-1)/2;u++)for(int v=1;v<=(p-1)/2;v++){if(md(u*u+v*v-2*(1+b*b),p))continue;array<vector<int>,4>L={pm(p,1),pm(p,b),pm(p,u),pm(p,v)};if(directN(p,L))continue;non++;if(!absorber2(p,L))fail.push_back({b,u,v});}if(non!=populations[p]||fail!=exp)return 1;cout<<"p="<<p<<": noncompletable="<<non<<", order-two exceptions="<<fail.size()<<"\n";}
vector<W> ws={{17,1,6,6,{{13,0},{7,5},{11,14}},{{1,5},{7,1},{11,0},{13,16},{16,14}}},{17,4,6,7,{{10,2},{15,8},{8,11}},{{1,11},{8,2},{10,13},{15,4},{16,8}}},{17,4,7,6,{{7,2},{8,6},{4,1}},{{1,13},{4,2},{7,4},{8,1},{16,6}}},{19,1,4,8,{{8,17},{10,10},{5,12}},{{1,10},{5,1},{8,12},{10,17},{18,18}}},{19,1,8,4,{{3,6},{17,4},{14,10}},{{1,4},{3,18},{14,1},{17,6},{18,10}}},{19,2,9,9,{{6,1},{7,4},{10,8}},{{1,17},{6,4},{7,2},{10,1},{18,8}}},{19,9,5,5,{{14,8},{12,0},{15,13}},{{1,8},{12,10},{14,0},{15,9},{18,13}}}};for(auto&w:ws)if(!verify_witness(w))return 1;cout<<"all seven order-three absorber certificates verified\n";}
