#include <bits/stdc++.h>
#include <omp.h>
using namespace std;
struct L{int a,b,c;bool operator==(L const&o)const{return a==o.a&&b==o.b&&c==o.c;}};
struct H{size_t operator()(L const&x)const noexcept{return ((uint64_t)(x.a+100)<<42)^((uint64_t)(x.b+100)<<32)^(uint32_t)(x.c+100000);}};
vector<int>pl;int C2[61],C3[61],INV[1771],NL;
L canon(int x1,int y1,int x2,int y2){int A=y2-y1,B=x1-x2,C=A*x1+B*y1,g=gcd(abs(A),gcd(abs(B),abs(C)));if(g)A/=g,B/=g,C/=g;if(A<0||(A==0&&B<0))A=-A,B=-B,C=-C;return{A,B,C};}
void init(){unordered_map<L,int,H>m;m.reserve(240000);pl.assign(810000,-1);int z=0;for(int u=0;u<900;u++)for(int v=u+1;v<900;v++){auto q=canon(u/30,u%30,v/30,v%30);auto[it,n]=m.emplace(q,z);if(n)z++;pl[u*900+v]=pl[v*900+u]=it->second;}NL=z;for(int k=0;k<=60;k++){C2[k]=k*(k-1)/2;C3[k]=k*(k-1)*(k-2)/6;INV[C2[k]]=k;}}
struct Job{array<unsigned char,7>re{},be{};unsigned char nr=0,nb=0;};
struct Sol{vector<int>R,B,rv,bv;array<unsigned char,30>rass{},bass{};int pot=99;};
struct Worker{vector<int>mark,freq,paircnt,touched,ids,cells,R,B,rv,bv;int stamp=1,pot=0;array<unsigned char,30>rass{},bass{},rused{},bused{};long long nodes=0;Worker():mark(NL),freq(NL),paircnt(NL){touched.reserve(1800);ids.reserve(60);cells.reserve(60);}void clear(){for(int id:touched)paircnt[id]=0;touched.clear();cells.clear();fill(rass.begin(),rass.end(),0);fill(bass.begin(),bass.end(),0);fill(rused.begin(),rused.end(),0);fill(bused.begin(),bused.end(),0);pot=0;}bool add_cell(int cell){if(++stamp==INT_MAX){fill(mark.begin(),mark.end(),0);stamp=1;}ids.clear();for(int q:cells){int id=pl[cell*900+q];if(mark[id]!=stamp){mark[id]=stamp;freq[id]=0;ids.push_back(id);}freq[id]++;}int delta=0;for(int id:ids)delta+=C2[freq[id]];if(pot+delta>2)return false;pot+=delta;cells.push_back(cell);return true;}void remove_cell(int oldpot){cells.pop_back();pot=oldpot;}bool build(const Job&j,const vector<int>&r0,const vector<int>&b0,const vector<int>&RB,const vector<int>&BB){clear();R=RB;B=BB;for(int k=0;k<j.nr;k++)R.push_back(j.re[k]);for(int k=0;k<j.nb;k++)B.push_back(j.be[k]);array<unsigned char,30>rm{},bm{};for(int x:R)rm[x]=1;for(int x:B)bm[x]=1;for(int i=0;i<30;i++){if(!rm[i]){rass[i]=r0[i];cells.push_back(i*30+r0[i]-1);}if(!bm[i]){bass[i]=b0[i];cells.push_back(i*30+b0[i]-1);}}for(int i=0;i<(int)cells.size();i++)for(int k=0;k<i;k++){int id=pl[cells[i]*900+cells[k]];if(paircnt[id]++==0)touched.push_back(id);}pot=0;for(int id:touched)pot+=C3[INV[paircnt[id]]];if(pot>2)return false;rv.clear();bv.clear();for(int x:R)rv.push_back(r0[x]);for(int x:B)bv.push_back(b0[x]);return true;}bool dfs(int depth,const vector<pair<int,int>>&ord,Sol&sol){nodes++;if(depth==(int)ord.size()){sol.R=R;sol.B=B;sol.rv=rv;sol.bv=bv;sol.rass=rass;sol.bass=bass;sol.pot=pot;return true;}auto[l,row]=ord[depth];auto&vals=l?bv:rv;auto&used=l?bused:rused;auto&ass=l?bass:rass;auto&opp=l?rass:bass;vector<int>ks(vals.size());iota(ks.begin(),ks.end(),0);stable_sort(ks.begin(),ks.end(),[&](int a,int b){return(vals[a]==ass[row])>(vals[b]==ass[row]);});for(int k:ks){int y=vals[k];if(used[k]||(opp[row]&&opp[row]==y))continue;int oldpot=pot;if(!add_cell(row*30+y-1))continue;used[k]=1;auto old=ass[row];ass[row]=y;if(dfs(depth+1,ord,sol))return true;ass[row]=old;used[k]=0;remove_cell(oldpot);}return false;}};
int main(int argc,char**argv){init();if(argc!=4)return 2;long long lo=atoll(argv[1]),hi=atoll(argv[2]),expected=atoll(argv[3]);vector<int>r0={12,15,24,9,27,20,4,17,28,29,6,2,8,13,1,18,7,19,23,11,26,30,10,5,14,3,21,22,25,16},b0={17,10,21,22,7,15,8,28,25,13,9,4,20,26,30,12,27,24,29,23,14,1,2,11,18,6,3,16,5,19},RB={13,15,19,22},BB={8,13,17,19,28},RE,BE;for(int i=0;i<30;i++){if(find(RB.begin(),RB.end(),i)==RB.end())RE.push_back(i);if(find(BB.begin(),BB.end(),i)==BB.end())BE.push_back(i);}vector<Job>jobs;vector<vector<int>>RC,BC;vector<int>cur;function<void(const vector<int>&,int,int,vector<vector<int>>&)>gen=[&](const vector<int>&a,int k,int st,vector<vector<int>>&out){if((int)cur.size()==k){out.push_back(cur);return;}for(int i=st;i<=(int)a.size()-(k-(int)cur.size());i++){cur.push_back(a[i]);gen(a,k,i+1,out);cur.pop_back();}};gen(RE,1,0,RC);cur.clear();gen(BE,6,0,BC);for(auto const&rr:RC)for(auto const&bb:BC){Job j;j.nr=1;j.nb=6;j.re[0]=rr[0];for(int i=0;i<6;i++)j.be[i]=bb[i];jobs.push_back(j);}if(lo<0||hi>(long long)jobs.size()||lo>=hi)return 3;atomic<bool>found(false);atomic<long long>done(0),nodes(0);Sol global;mutex mu;
#pragma omp parallel num_threads(8)
{Worker w;Sol local;
#pragma omp for schedule(dynamic,1)
for(long long ji=lo;ji<hi;ji++){if(found.load(memory_order_relaxed))continue;auto&j=jobs[ji];if(!w.build(j,r0,b0,RB,BB)){done++;continue;}vector<pair<int,int>>ord;for(int x:w.R)ord.push_back({0,x});for(int x:w.B)ord.push_back({1,x});stable_sort(ord.begin(),ord.end(),[&](auto a,auto b){int oa=a.first?w.rass[a.second]:w.bass[a.second],ob=b.first?w.rass[b.second]:w.bass[b.second];return(oa!=0)>(ob!=0);});if(w.dfs(0,ord,local)){bool exp=false;if(found.compare_exchange_strong(exp,true)){lock_guard<mutex>lk(mu);global=local;}}done++;nodes+=w.nodes;w.nodes=0;}}
if(found){cerr<<"unexpected potential-at-most-two endpoint\n";return 1;}assert(done==hi-lo&&nodes==expected);cout<<"AC p31 support-seven (1,6) shard\n"<<"support_lo: "<<lo<<"\n"<<"support_hi: "<<hi<<"\n"<<"support_choices: "<<done<<"\n"<<"partial_states: "<<nodes<<"\n"<<"complete_potential_at_most_two_states: 0\n";return 0;}
